//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentPlanner.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int Id { get; set; }
        public byte AssignmentTypeId { get; set; }
        public int ContractId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<double> TotalRegularTimeHours { get; set; }
        public Nullable<double> TotalHolidayHours { get; set; }
        public Nullable<double> TotalWeekEndHours { get; set; }
        public Nullable<double> TotalNightTimeHours { get; set; }
        public Nullable<double> RegularHoursRate { get; set; }
        public Nullable<double> HolidayHoursRate { get; set; }
        public Nullable<double> WeekHoursRate { get; set; }
        public Nullable<double> NightTimeHoursRate { get; set; }
    
        public virtual AssignmentType AssignmentType { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
